runtime: python
api_version: 1
threadsafe: true
env: flex
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  
libraries:
- name: PIL
  version: latest