runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

  

libraries:
- name: PIL
  version: "latest"
- name: numpy
  version: "latest"
- name: Flask
  version: "0.10"
